spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
  datasource:
    #url: "jdbc:h2:file:./target/h2db"
    #name: "test"
    #username: "sa"
    #password: ""
    #driver-class-name : "org.h2.Driver"
#    url: "jdbc:postgresql://localhost:5432/log?currentSchema=log"
#    username: "postgres"
#    password: "password"
#    driver-class-name : "org.postgresql.Driver"
     url: "jdbc:mysql://localhost:3306/flyway"
     username: "root"
     password: "password"
     driver-class-name : "org.mariadb.jdbc.Driver"
mybatis:
  config-location: "classpath:mybatis-config.xml"
  type-handlers-package: "com.github.apz.springsample.typehandler"
  mapper-locations: classpath*:/mybatis-mapper/**/*.xml

  