INSERT INTO ACTIVE_DAY_OF_WEEK (ID, DAY_OF_WEEK) VALUES (1, 1);
INSERT INTO ACTIVE_DAY_OF_WEEK (ID, DAY_OF_WEEK) VALUES (1, 2);
INSERT INTO ACTIVE_DAY_OF_WEEK (ID, DAY_OF_WEEK) VALUES (1, 3);
INSERT INTO ACTIVE_DAY_OF_WEEK (ID, DAY_OF_WEEK) VALUES (1, 4);
INSERT INTO ACTIVE_DAY_OF_WEEK (ID, DAY_OF_WEEK) VALUES (1, 5);

INSERT INTO ACTIVE_DAY_OF_WEEK (ID, DAY_OF_WEEK) VALUES (2, 0);
INSERT INTO ACTIVE_DAY_OF_WEEK (ID, DAY_OF_WEEK) VALUES (2, 5);
INSERT INTO ACTIVE_DAY_OF_WEEK (ID, DAY_OF_WEEK) VALUES (2, 6);
INSERT INTO ACTIVE_DAY_OF_WEEK (ID, DAY_OF_WEEK) VALUES (2, 7);

INSERT INTO ACTIVE_DAY_OF_WEEK (ID, DAY_OF_WEEK) VALUES (3, 6);